version: '3'
services:
  consul:
    image: consul:1.8.4
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  customer:
    build: ../microservice-consul-demo/microservice-consul-demo-customer
    links:
     - consul
     - zipkin
    environment:
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411/"
  catalog:
    build: ../microservice-consul-demo/microservice-consul-demo-catalog
    links:
     - consul
     - zipkin
    environment:
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411/"
  order:
    build: ../microservice-consul-demo/microservice-consul-demo-order
    links:
     - consul
     - zipkin
    environment:
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411/"
  apache:
    build: apache
    links:
     - consul
    depends_on:
     - consul
    ports:
     - "8080:80"
  zipkin:
    image: openzipkin/zipkin:2.21.7
    ports:
     - "9411:9411"